language: csharp
mono: none
dist: bionic
dotnet: 3.0

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
  - dotnet restore

script:
  - dotnet build -c Release